### im-demo.yaml
###
### SigScale IM one shot demo instance created from empty db dir
###
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sigscale-im
  labels:
    app.kubernetes.io/name: im
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: im
  template:
    metadata:
      labels:
        app.kubernetes.io/name: im
        app.kubernetes.io/component: rest
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
      - name: im-init
        image: asia.gcr.io/sigscale-oss/im
        stdin: true
        tty: true
        command:
        - bin/initialize
        volumeMounts:
        - mountPath: /home/otp/db
          name: db
      containers:
      - name: im
        image: asia.gcr.io/sigscale-oss/im
        stdin: true
        tty: true
        ports:
        - name: rest
          protocol: TCP
          containerPort: 8080
        volumeMounts:
        - mountPath: /home/otp/db
          name: db
      volumes:
      - name: db
        emptyDir: {}
