### sigscale-rim-odl.yaml
###
###
apiVersion: oda.tmforum.org/v1alpha3
kind: component
metadata:
  name: sigscale-rim
  labels:
    oda.tmforum.org/componentName: sigscale-rim
spec:
  type: rim
  selector:
    matchLabels:
     oda.tmforum.org/componentName: sigscale-rim
  componentKinds:
    - group: core
      kind: Service
    - group: apps
      kind: StatefulSet
    - group: core
      kind: Secret
  version: "2.0.2"
  description: "SigScale Resource Inventory Management (RIM)"
  maintainers:
    - name: SigScale
      email: support@sigscale.com
  owners:
    - name: SigScale
      email:  support@sigscale.com
  coreFunction:
    exposedAPIs:
    - name: party
      specification: https://github.com/tmforum/TMFAPISWAGGER/blob/develop/partyManagement/v2/swagger2.json
      implementation: sigscale-rim-rest
      path: /partyManagement/v2/
      port: 8080
    - name: resourceCatalog
      specification: https://github.com/tmforum-apis/TMF620_ProductCatalog/blob/master/TMF620-ProductCatalog-v4.0.0.swagger.json
      implementation: sigscale-rim-rest
      path: /resourceCatalogManagement/v4/
      port: 8080
    - name: resourceInventory
      specification: https://github.com/tmforum-apis/TMF639_ResourceInventory/blob/master/TMF639-ResourceInventory-v4.0.0.swagger.json
      implementation: sigscale-rim-rest
      path: /resourceInventoryManagement/v4/
      port: 8080
    dependantAPIs: []
  eventNotification:
    publishedEvents: []
    subscribedEvents: []
  management: []
  security:
    controllerRole: admin
    securitySchemes:
      bearerAuth:
        type: http
        scheme: bearer
        bearerFormat: JWT
    partyrole:
      implementation: sigscale-rim-partyrole
      path: /partyRoleManagement/v4/
      port: 8090
