## SigScale IM REST Service for Security
##
kind: Service
apiVersion: v1
metadata:
  name: sigscale-rim-partyrole
  labels:
    app.kubernetes.io/name: im
    oda.tmforum.org/componentName: sigscale-rim
spec:
  selector:
    app.kubernetes.io/component: im-node
  type: NodePort
  ports:
  - protocol: TCP
    appProtocol: http
    port: 8090
    targetPort: rest
