## SigScale IM REST Service
##
kind: Service
apiVersion: v1
metadata:
  name: sigscale-rim-service
  labels:
    app.kubernetes.io/name: im
    oda.tmforum.org/componentName: sigscale-rim
spec:
  selector:
    app.kubernetes.io/component: oam
  type: NodePort
  ports:
  - protocol: TCP
    appProtocol: http
    port: 8080
    targetPort: rest
