### Erlang/OTP Distribution Secrets
kind: Secret
apiVersion: v1
metadata:
  name: otp-dist
  labels:
    oda.tmforum.org/componentName: sigscale-rim
type: Opaque
data:
  ERLANG_COOKIE: SllGWFJZQkhPV0lNWVlLQUlITkI=
